server {
    listen 80;
    index index.php index.html login.php koneksi.php;
    root /var/www/html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Aturan untuk memproses file PHP menggunakan kontainer 'app'
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # Teruskan permintaan ke kontainer 'app' pada port 9000
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}